#!/usr/bin/env python3

import ncplugin
import NCrystal as NC
import numpy as np
import matplotlib.pyplot as plt
ncplugin.registerPlugin()#<---register our plugin with NCrystal


# sc_plugin = NC.createScatter("testcode/data/custom.ncmat;packfact=1")
sc_plugin = NC.createScatter("testcode/data/nc.ncmat")
wls = np.linspace(1,20.0,1000)
plt.loglog( wls, sc_plugin.xsect(wl=wls), label='With new plugin' )

plt.xlabel('angstrom')
plt.ylabel('barn')
plt.legend()
plt.grid()
plt.show()
