#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# sasview2ncmat.py - convert a SasView-exported I(Q) curve into an NCMAT file
#                    that uses the DirectLoad mode of the SasCSNS NCrystal
#                    plugin (@CUSTOM_SASCSNS section).
#
# SasView (https://www.sasview.org) can export 1D fitting data as plain ASCII
# files with columns like "Q (1/A)  I (1/cm)  dI  dQ" (header lines start
# with "#"). This script converts such a file into NCMAT v6 data:
#
#   python3 sasview2ncmat.py sasview_iq.dat -o sas_model.ncmat \
#           --material sio2 --density 2.2 --phi 0.4 --radius 100.0
#
# Unit conversion (ALWAYS applied - there is deliberately no flag for it):
#   SasView reports intensity in barn per OBJECT (particle), while NCrystal
#   expects barn per ATOM. The converter therefore multiplies every I value
#   by scale = n_objects / n_atoms = (phi / V_p) / n_d, where phi is the
#   particle volume fraction, V_p the particle volume and n_d the atomic
#   number density of the file material (computed from --material and
#   --density). The scale used is recorded in the output file header.
#
# The resulting NCMAT file requires the SasCSNS plugin:
#   nctool sas_model.ncmat
# -----------------------------------------------------------------------------
import argparse
import math
import sys

AVOGADRO = 6.02214076e23  # 1/mol


def read_sasview_iq(filename):
    """Read a SasView-exported ASCII I(Q) file, return sorted [(Q, I)] list."""
    points = []
    with open(filename) as fh:
        for ln in fh:
            s = ln.strip()
            if not s or s.startswith('#'):
                continue
            parts = s.replace(',', ' ').split()
            if len(parts) < 2:
                continue
            try:
                q, i = float(parts[0]), float(parts[1])
            except ValueError:
                continue  # column-title or metadata line
            points.append((q, i))
    if len(points) < 2:
        sys.exit(f'ERROR: found fewer than 2 (Q,I) points in {filename}')
    # Sort ascending in Q, drop NaN/negative-I points and duplicated Q values:
    points = sorted((q, i) for q, i in points if q > 0.0 and i > 0.0)
    deduped = []
    for q, i in points:
        if deduped and abs(q - deduped[-1][0]) < 1.0e-12:
            continue
        deduped.append((q, i))
    return deduped


MATERIAL_PRESETS = {
    # name: (list of (element, fraction))
    'sio2': [('Si', 0.3333333), ('O', 0.6666667)],
    'al2o3': [('Al', 0.4), ('O', 0.6)],
    'fe3o4': [('Fe', 0.4285714), ('O', 0.5714286)],
    'air': [('N', 0.76), ('O', 0.24)],
}

ATOMIC_MASS = {  # g/mol (standard atomic weights)
    'Si': 28.085, 'O': 15.999, 'Al': 26.9815, 'Fe': 55.845, 'N': 14.007,
}


def number_density(material, density):
    """Atomic number density [1/Aa^3] of a material preset at given density."""
    composition = resolve_material(material)
    mass_batch = sum(frac * ATOMIC_MASS[el] for el, frac in composition)
    atoms_batch = sum(frac for _, frac in composition)
    # n_d = rho * N_A * atoms_batch / M_batch, converted cm^-3 -> Aa^-3:
    return density * AVOGADRO * atoms_batch / (mass_batch * 1.0e24)


def resolve_material(material):
    try:
        return MATERIAL_PRESETS[material.lower()]
    except KeyError:
        sys.exit(f'ERROR: unknown material {material!r} '
                 f'(known: {", ".join(sorted(MATERIAL_PRESETS))})')


def write_ncmat(out, points, material, density, radius, solvent, scale):
    composition = resolve_material(material)
    lines = ['NCMAT v6',
             '#',
             '# Generated by sasview2ncmat.py from a SasView-exported I(Q) curve.',
             '# Scattering model: SasCSNS plugin, DirectLoad mode'
             + (f' with solvent {solvent}' if solvent else ' (vacuum solvent)'),
             '#',
             f'# Unit conversion applied (SasView barn/object -> NCrystal barn/atom):',
             f'#   I_ncmat = I_sasview * {scale:.8g}',
             f'#   scale = (phi / V_p) / n_d'
             + (f' with V_p = 4/3*pi*R^3, R = {radius:g} Aa (sphere)' if radius else ''),
             '#']
    for q, i in points:
        lines.append(f'#   Q={q:<12.6g} I={i * scale:<12.6g}')
    lines += ['',
              f'@DENSITY',
              f'  {density} g_per_cm3']
    for element, frac in composition:
        lines += ['@DYNINFO',
                  f'  element {element}',
                  f'  fraction {frac}',
                  '  type freegas']
    lines += ['@CUSTOM_SASCSNS',
              '  DirectLoad',
              '  Q ' + ' '.join(f'{q:.6g}' for q, _ in points),
              '  I ' + ' '.join(f'{i * scale:.6g}' for _, i in points)]
    if solvent:
        lines.append(f'  solvent {solvent}')
    lines.append('')
    with open(out, 'w') as fh:
        fh.write('\n'.join(lines))


def main():
    ap = argparse.ArgumentParser(
        description='Convert a SasView-exported I(Q) curve into an NCMAT file '
                    'for the SasCSNS NCrystal plugin (DirectLoad mode). The '
                    'barn/object -> barn/atom unit conversion is always applied, '
                    'computed from the mandatory physical parameters below.')
    ap.add_argument('sasview_file', help='SasView ASCII data file (Q I [dI] [dQ] columns)')
    ap.add_argument('-o', '--output', default='sas_model.ncmat',
                    help='output NCMAT file name (default: %(default)s)')
    ap.add_argument('--material', default='sio2',
                    help='particle material preset: ' + ', '.join(sorted(MATERIAL_PRESETS))
                         + ' (default: %(default)s)')
    ap.add_argument('--density', type=float, default=2.2,
                    help='particle material density in g/cm3 (default: %(default)s)')
    ap.add_argument('--phi', type=float, required=True,
                    help='particle volume fraction in the sample (mandatory)')
    vgroup = ap.add_mutually_exclusive_group(required=True)
    vgroup.add_argument('--radius', type=float,
                        help='particle radius in Angstrom, for spherical particles '
                             '(V_p = 4/3*pi*R^3)')
    vgroup.add_argument('--volume', type=float,
                        help='particle volume in Angstrom^3, for non-spherical particles')
    ap.add_argument('--solvent', default='',
                    help='solvent material name, stored as a comment for '
                         'reference (DirectLoad I(Q) already includes solvent '
                         'contrast; default: none)')
    args = ap.parse_args()

    if not 0.0 < args.phi < 1.0:
        sys.exit(f'ERROR: --phi must be in (0,1), got {args.phi}')

    n_d = number_density(args.material, args.density)
    if args.radius is not None:
        if args.radius <= 0.0:
            sys.exit(f'ERROR: --radius must be positive, got {args.radius}')
        v_p = 4.0 / 3.0 * math.pi * args.radius**3
    else:
        if args.volume <= 0.0:
            sys.exit(f'ERROR: --volume must be positive, got {args.volume}')
        v_p = args.volume
    scale = (args.phi / v_p) / n_d  # barn/object -> barn/atom

    points = read_sasview_iq(args.sasview_file)
    write_ncmat(args.output, points, args.material, args.density,
                args.radius, args.solvent, scale)
    print(f'Wrote {args.output} with {len(points)} (Q,I) points from '
          f'{args.sasview_file}')
    print(f'Unit conversion (always applied): scale = (phi/V_p)/n_d = '
          f'({args.phi:g}/{v_p:.6g})/{n_d:.6g} = {scale:.8g} '
          f'[barn/object -> barn/atom]')
    print('Load it with NCrystal, e.g.:  nctool '
          f'{args.output} -x 1e-5 1.0 -p')


if __name__ == '__main__':
    main()
