#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# sasview2ncmat.py - convert a SasView-exported I(Q) curve into an NCMAT file
#                    that uses the DirectLoad mode of the SasCSNS NCrystal
#                    plugin (@CUSTOM_SASCSNS section).
#
# SasView (https://www.sasview.org) can export 1D fitting data as plain ASCII
# files with columns like "Q (1/A)  I (1/cm)  dI  dQ" (header lines start
# with "#"). This script converts such a file into NCMAT v6 data:
#
#   python3 sasview2ncmat.py sasview_iq.dat -o sas_model.ncmat \
#           --material sio2 --density 2.2 --radius 100.0
#
# The resulting NCMAT file requires the SasCSNS plugin:
#   nctool sas_model.ncmat
# -----------------------------------------------------------------------------
import argparse
import sys


def read_sasview_iq(filename):
    """Read a SasView-exported ASCII I(Q) file, return sorted [(Q, I)] list."""
    points = []
    with open(filename) as fh:
        for ln in fh:
            s = ln.strip()
            if not s or s.startswith('#'):
                continue
            parts = s.replace(',', ' ').split()
            if len(parts) < 2:
                continue
            try:
                q, i = float(parts[0]), float(parts[1])
            except ValueError:
                continue  # column-title or metadata line
            points.append((q, i))
    if len(points) < 2:
        sys.exit(f'ERROR: found fewer than 2 (Q,I) points in {filename}')
    # Sort ascending in Q, drop NaN/negative-I points and duplicated Q values:
    points = sorted((q, i) for q, i in points if q > 0.0 and i > 0.0)
    deduped = []
    for q, i in points:
        if deduped and abs(q - deduped[-1][0]) < 1.0e-12:
            continue
        deduped.append((q, i))
    return deduped


MATERIAL_PRESETS = {
    # name: (list of (element, fraction))
    'sio2': [('Si', 0.3333333), ('O', 0.6666667)],
    'al2o3': [('Al', 0.4), ('O', 0.6)],
    'fe3o4': [('Fe', 0.4285714), ('O', 0.5714286)],
    'air': [('N', 0.76), ('O', 0.24)],
}


def write_ncmat(out, points, material, density, radius, solvent, scale=1.0):
    try:
        composition = MATERIAL_PRESETS[material.lower()]
    except KeyError:
        sys.exit(f'ERROR: unknown material {material!r} '
                 f'(known: {", ".join(sorted(MATERIAL_PRESETS))})')
    lines = ['NCMAT v6',
             '#',
             '# Generated by sasview2ncmat.py from a SasView-exported I(Q) curve.',
             '# Scattering model: SasCSNS plugin, DirectLoad mode'
             + (f' with solvent {solvent}' if solvent else ' (vacuum solvent)'),
             '#']
    for q, i in points:
        lines.append(f'#   Q={q:<12.6g} I={i:<12.6g}')
    lines += ['',
              f'@DENSITY',
              f'  {density} g_per_cm3']
    for element, frac in composition:
        lines += ['@DYNINFO',
                  f'  element {element}',
                  f'  fraction {frac}',
                  '  type freegas']
    lines += ['@CUSTOM_SASCSNS',
              '  DirectLoad',
              '  Q ' + ' '.join(f'{q:.6g}' for q, _ in points),
              '  I ' + ' '.join(f'{i*scale:.6g}' for _, i in points)]
    if solvent:
        lines.append(f'  solvent {solvent}')
    lines.append('')
    with open(out, 'w') as fh:
        fh.write('\n'.join(lines))


def main():
    ap = argparse.ArgumentParser(
        description='Convert a SasView-exported I(Q) curve into an NCMAT file '
                    'for the SasCSNS NCrystal plugin (DirectLoad mode).')
    ap.add_argument('sasview_file', help='SasView ASCII data file (Q I [dI] [dQ] columns)')
    ap.add_argument('-o', '--output', default='sas_model.ncmat',
                    help='output NCMAT file name (default: %(default)s)')
    ap.add_argument('--material', default='sio2',
                    help='sphere material preset: ' + ', '.join(sorted(MATERIAL_PRESETS))
                         + ' (default: %(default)s)')
    ap.add_argument('--density', type=float, default=2.2,
                    help='sphere material density in g/cm3 (default: %(default)s)')
    ap.add_argument('--radius', type=float, default=100.0,
                    help='sphere radius in Angstrom, stored as a comment for '
                         'reference (the DirectLoad I(Q) already includes the '
                         'form factor; default: %(default)s)')
    ap.add_argument('--scale', type=float, default=1.0,
                    help='factor applied to the I values. Use this for unit '
                         'conversion: SasView reports I in barn per OBJECT '
                         '(per particle), while NCrystal expects barn per '
                         'ATOM, i.e. scale = n_particles_per_A3 / n_atoms_per_A3 '
                         'of the target material (default: %(default)s)')
    ap.add_argument('--solvent', default='',
                    help='solvent material name, stored as a comment for '
                         'reference (DirectLoad I(Q) already includes solvent '
                         'contrast; default: none)')
    args = ap.parse_args()

    points = read_sasview_iq(args.sasview_file)
    write_ncmat(args.output, points, args.material, args.density,
                args.radius, args.solvent, args.scale)
    print(f'Wrote {args.output} with {len(points)} (Q,I) points from '
          f'{args.sasview_file}')
    print('Load it with NCrystal, e.g.:  nctool '
          f'{args.output} -x 1e-5 1.0 -p')


if __name__ == '__main__':
    main()
